services:
  app:
    build:
      context: .
      target: builder
    ports:
      - "6006:6006"
    volumes:
      - .:/app
      - /app/node_modules

  docs:
    image: node:26-alpine
    working_dir: /app
    command: sh -c "npm install && npm start -- --host 0.0.0.0"
    volumes:
      - ./website:/app
      - /app/node_modules
    ports:
      - "3000:3000"
