services:
  app:
    build:
      context: .
      target: builder
    ports:
      - "6006:6006"
    volumes:
      - .:/app
      - /app/node_modules

  docs:
    image: squidfunk/mkdocs-material:latest
    volumes:
      - .:/docs
    ports:
      - "8000:8000"
